# render.yaml

services:
  - name: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /
    envVars:
      FLASK_ENV: production
      SECRET_KEY: your_secret_key_here
      DATABASE_URL: sqlite:///data.db
